---
dev:
  app_function: noticeinsite.app
  s3_bucket: noticeiniste-app.arlindo.ca
  keep_warm: true
  memory_size: 128
  profile_name: arlindo
  certificate_arn: arn:aws:acm:us-east-1:866453871771:certificate/5df06db6-73b2-4efd-b195-a13979341176
  domain: noticeinsite.dev.tsxtrust.com
  cache_cluster_enabled: false
  cloudwatch_metrics_enabled: true
  cloudwatch_log_level: OFF  
